IO.puts(2 + 2)
IO.puts(2 + 3 == 5)
IO.puts(String.length("hello world"))
IO.puts(3)
IO.puts(3.14)
IO.puts(1.0e-10)
IO.puts(true)
IO.puts(false)
IO.puts(:foo)
IO.puts(:foo == :bar)
IO.puts(true |> is_atom)
IO.puts(:true |> is_atom)
IO.puts(:true == true)
IO.puts(is_atom(MyApp.MyModule))
IO.puts("hello")
IO.puts("dziękuję")
IO.puts("foo\nbar")
IO.puts(2+2)
IO.puts(2-1)
IO.puts(2*5)
IO.puts(10/5)
IO.puts(div(10, 5))
IO.puts(rem(10, 3))
IO.puts(-20 || true)
IO.puts(false || 42)
IO.puts(42 && true)
IO.puts(42 && nil)
IO.puts(!42)
IO.puts(!false)
IO.puts(2 == 2.0)
IO.puts(2 === 2.0)
IO.puts({:hello, :world} > [1, 2, 3])
name = "Sean"
IO.puts("Hello #{name}")
IO.puts("hello " <> name)

