#
# @lc app=leetcode id=389 lang=python
#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (52.80%)
# Total Accepted:    138.3K
# Total Submissions: 261.9K
# Testcase Example:  '"abcd"\n"abcde"'
#
#
# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.
#
#


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ans = 0
        for i in s:
            ans ^= ord(i)
        for i in t:
            ans ^= ord(i)
        return chr(ans)

    def findTheDifference1(self, s, t):
        d = {}
        for i in s:
            d[i] = d.get(i, 0) + 1
        for i in t:
            d[i] = d.get(i, 0) - 1
        for i in t:
            if d.get(i) < 0:
                return i
        return ''
