name:                haskell-programming-for-first-principles
version:             0.1.0.0
github:              "githubuser/haskell-programming-for-first-principles"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-programming-for-first-principles#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta
- raw-strings-qq
- bytestring
- containers
- hspec
- aeson
- text
- scientific
- megaparsec
- mtl
- parsec
- haskeline
- transformers
- criterion
- vector
- zlib

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-programming-for-first-principles-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-programming-for-first-principles

tests:
  haskell-programming-for-first-principles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-programming-for-first-principles
